language: node_js
sudo: required
cache: false
os:
  - linux
node_js:
  - "12.11.0"

services:
  - xvfb

addons:
  chrome: stable
  firefox: stable

script:
- echo "versions"
- openssl version
- node -v
- npm install
- npm run lint
- npm run build
- npm run test:node
- travis_retry npm run test:browser
- npm run test:typings
- npm run test:deps
- npm run test:size
- npm run build:size
